project_id = "ubrxhheuglfwwwbrgrvf"

[functions.payevo-pix]
verify_jwt = false

[functions.payevo-webhook]
verify_jwt = false

[functions.payevo-status]
verify_jwt = false

[functions.hypepay-pix]
verify_jwt = false

[functions.hypepay-webhook]
verify_jwt = false

[functions.pix-gateway]
verify_jwt = false

[functions.send-google-conversion]
verify_jwt = false

[functions.send-meta-conversion]
verify_jwt = false

[functions.send-utmify-event]
verify_jwt = false